format_version: v1.0
type: UniqueComponent
attributes: {id: sysOtaPic32mzw1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_OTA_AUTORESET_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: SYS_OTA_AUTOUPDATE_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: SYS_OTA_PERODIC_UPDATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: SYS_OTA_TIME_INTERVAL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: SYS_OTA_URL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'https://mu-otaserver.s3.amazonaws.com/simple_iot_application_manifest.json'}
- type: ElementPosition
  attributes: {x: '260', y: '20', id: sysOtaPic32mzw1}
