format_version: v1.0
type: UniqueComponent
attributes: {id: sysOtaPic32mzw1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_OTA_PERODIC_UPDATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: SYS_OTA_TIME_INTERVAL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '487', y: '159', id: sysOtaPic32mzw1}
