format_version: v1.0
type: UniqueComponent
attributes: {id: sysMqttPic32mzw1}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: SYS_MQTT_BROKER_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: io.adafruit.com}
  - type: Boolean
    attributes: {id: SYS_MQTT_ENABLE_DEBUG}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: SYS_MQTT_EXTRA_CRED}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: SYS_MQTT_PASSWORD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ''}
  - type: Boolean
    attributes: {id: SYS_MQTT_PUB_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: SYS_MQTT_PUB_TOPIC_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ../feeds/firmware-version}
  - type: Boolean
    attributes: {id: SYS_MQTT_SUB_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: SYS_MQTT_SUB_TOPIC_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ../feeds/otatrigger}
  - type: String
    attributes: {id: SYS_MQTT_USER_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ''}
- type: ElementPosition
  attributes: {x: '131', y: '297', id: sysMqttPic32mzw1}
