format_version: v1.0
type: UniqueComponent
attributes: {id: sysOtaPic32mzw1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_OTA_AUTORESET_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SYS_OTA_AUTOUPDATE_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SYS_OTA_PERODIC_UPDATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: SYS_OTA_TIME_INTERVAL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: String
    attributes: {id: SYS_OTA_URL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'https://raw.githubusercontent.com/MicrochipTech/mu-wfi32-ota-updates/main/json_manifest/ota_manifest.json'}
- type: ElementPosition
  attributes: {x: '305', y: '204', id: sysOtaPic32mzw1}
