configName: simple_iot_application
folderName: simple_iot_application
format_version: v1.0
frameworkPath: ..\..\..
processor: PIC32MZ1025W104132
projectName: simple_iot_application
settings:
  CMSISPath: ./dev_packs/arm/CMSIS/5.8.0
  DFPPath: ./dev_packs/Microchip/PIC32MZ-W_DFP/1.5.203/atdf/PIC32MZ1025W104132.atdf
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  MERGE_STRATEGY: ALL
  PackageFilter: crypto;dev_packs;net;core;bsp;quick_docs;wireless_wifi;csp;wireless_system_pic32mzw1_wfi32e01
  TRUSTZONE: 'false'
